variables:
  GIT_SSL_NO_VERIFY: "true"

stages:
  - get-versioning
  - build_push_docker
  - package-push-helm

versioning:
  stage: get-versioning
  image: ${DOCKER_REGISTRY}/chaos/git-semver:0.3.11
  tags:
    - docker
  script:
    - /entrypoint.sh ${CI_PROJECT_DIR} >> BUILD_VERSION
  artifacts:
    paths: [BUILD_VERSION]

build-docker:
  stage: build_push_docker
  tags:
    - docker
  image: docker:latest
  before_script:
    - |
      for i in $(seq 1 30); do
          if ! docker info &> /dev/null; then
              echo "Docker not responding yet. Sleeping for 2s..." && sleep 2s
          else
              echo "Docker ready. Continuing build..."
              break
          fi
      done

  script:
    - docker info
    - docker build --network=host . -f docker/Dockerfile -t ${DOCKER_REGISTRY}/${CI_PROJECT_ROOT_NAMESPACE}/${CI_PROJECT_NAME}:$(cat BUILD_VERSION)
    - docker push ${DOCKER_REGISTRY}/${CI_PROJECT_ROOT_NAMESPACE}/${CI_PROJECT_NAME}:$(cat BUILD_VERSION)
    - echo "${DOCKER_REGISTRY}/${CI_PROJECT_ROOT_NAMESPACE}/${CI_PROJECT_NAME}:$(cat BUILD_VERSION)" | tee DOCKER_IMAGE_VERSION

  artifacts:
    paths: [DOCKER_IMAGE_VERSION]

package-push-helm:
  stage: package-push-helm
  image: ${DOCKER_REGISTRY}/chaos/helm-tool:v0.1.0
  tags:
    - docker

  before_script:
    - helm repo add litmus-repo ${HELM_REGISTRY}
    - helm repo update

  script:
    - helm dependency update helm/${CI_PROJECT_NAME}
    - helm lint helm/${CI_PROJECT_NAME}
    - helm package helm/${CI_PROJECT_NAME} --version=$(cat BUILD_VERSION)
    - helm push-artifactory ${CI_PROJECT_NAME}-$(cat BUILD_VERSION).tgz litmus-repo --skip-reindex
